### ISSUE TITLE
Is possible to add n-gram words network 

### ISSUE THREAD

**Issue by Atsaniik** [jboynyc/textnets#26]
Is possible to add n-gram words network instead of just 1-gram, that would be more useful. 

Thanks for your great work.

**Comment by jboynyc** [comment]
You mean as an alternative to `.tokenized()` and `.noun_phrases()`? Perhaps something like `.ngrams(n=[2, 3])` for bi- and trigrams? That's an interesting idea -- I'll think about it. Would you want support for removing stop words, stemming etc. in such a feature?

**Comment by Atsaniik** [comment]
Thanks for your prompt reply. 

There is simple example as follows:

text1 = 'I do not like green apple but red apple'
text2 = 'I liked  apple'
text3= 'I neither hate nor like green apple'

tn.plot shows 'like' and 'apple'  are the common words for all 3 texts. but text1 and text3 actually say: 'not like' and 'green apple or red apple' in real life.

Thanks again for your great works.

**Comment by jboynyc** [comment]
Hi @pengKiina, I now have the beginnings of an implementation in the `dev` branch. The method of the `Corpus` class currently looks like this:

```python
def ngrams(
  self,
  size: int,
  remove: List[str] = [],
  stem: bool = False,
  remove_stop_words: bool = False,
  remove_urls: bool = True,
  remove_numbers: bool = True,
  remove_punctuation: bool = True,
  lower: bool = True,
) -> pd.DataFrame: ...
```

So you can say `corpus.ngrams(2)` for bigrams or `corpus.ngrams(3)` for trigrams. By default it removes numbers, URLs and punctuation (mirroring the `tokenized` method), but it does not stem words or remove stop words (unlike `tokenized`). I'm still unsure about these defaults. Maybe I'll just have everything default to `False` since numbers or URLs are likely often significant parts of n-grams.

I also wonder whether it may make sense to generate n-grams of various sizes at once, so that the `size` argument could take either an individual integer or a tuple of several integers. However, I guess that way we may end up with a network that contains both "like green apple" and "green apple," so I think it makes sense to restrict it to n-grams of one size.

Let me know whether you have any thoughts about this -- it would help to have some input before I make a release that includes this.

**Comment by jboynyc** [comment]
~~I *think* the current implementation also assumes that words are space-delimited, which isn't the case in some languages that `textnets` tries to support (e.g., Chinese). I'll have to see whether that's the case and, if so, how I can find a solution that works for both cases.~~

Update: Never mind.
