### ISSUE TITLE
In pandas dataframe with repeated labels, how to transfer data into 'Corpus' object?

### ISSUE THREAD

**Issue by onigiricoco** [jboynyc/textnets#54]
Hi. I noticed in `tn.Corpus.from_df(df, doc_col="tekst", lang="nl")` , the label must be the index of dataframe. However, if I have repeated labels (in a classification task, my labels are 1,1,1,0,0,1,0,...), the algorithm gets stuck and my ram exploded.

![image](https://user-images.githubusercontent.com/93609152/213581497-41277316-6a90-44a6-b725-0064376fcf02.png)
 Could you tell me how to fill in the parameters? I want to build the network of words between label 0 and label 1.

Thank you!

**Comment by jboynyc** [comment]
I suggest you use [groupby](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html) to concatenate all the documents into one long string per label. Something like the following should work:

```
new_df = df.groupby("label").agg({"news": "\n".join})
```

Feel free to reopen if this doesn't solve your issue.

**Comment by jboynyc** [comment]
Note to self: Perhaps `Corpus` should raise an error if there are repeated document labels. I don't think documents with identical labels should be concatenated by default, because repeated labels may be the result of an error. 

Another option would be to concatenate them and `warn` that it occurred.
